apiVersion: v1
kind: ConfigMap
metadata:
  name: config-nginx
  namespace: nginx
data:
  nginx.conf: |
    server {
      listen 80;
      listen 443 ssl;
      root /usr/share/nginx/html;
      ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
      ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    }