apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
